services:
  polybot:
    image: berko1/${POLYBOT_IMG_NAME}:latest
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_APP_URL=${TELEGRAM_APP_URL}
      - MONGO_URI=${MONGO_URI}
      - BUCKET_NAME=${BUCKET_NAME}
    ports:
      - "8081:8081"
    depends_on:
      - yolo5
      - mongo

  yolo5:
    image: berko1/${YOLO5_IMG_NAME}:latest
    environment:
      - MONGO_URI=${MONGO_URI}
      - BUCKET_NAME=${BUCKET_NAME}
    ports:
      - "5000:5000"
    networks:
      - mongoCluster
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    deploy:
      replicas: 3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: >
      bash -c "
            mongod --replSet myReplicaSet --bind_ip_all &&
            sleep 5 &&
            echo 'Initializing replica set' &&
            mongosh --eval '
              rs.initiate({
                _id: \"myReplicaSet\",
                members: [
                  {_id: 0, host: \"mongo1\"},
                  {_id: 1, host: \"mongo2\"},
                  {_id: 2, host: \"mongo3\"}
                ]
              })'"
    networks:
      - mongoCluster
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"

networks:
  mongoCluster:
    driver: bridge